### ISSUE TITLE
The animation doesn't work

### ISSUE THREAD

**Issue by Evpok** [Evpok/fancy-bracket-matcher#1]
May or may not be related to https://github.com/atom/atom/issues/4590. Actually if brackets are highlighted and you switch tabs, there *is* an animation.

**Comment by unkndono** [comment]
Hi, 
As said in this discussion : https://discuss.atom.io/t/bracket-matcher-animation/15648/6
it's possible to do animations within a simple package

**Comment by Evpok** [comment]
Indeed it did. Thanks for the head up!
