### ISSUE TITLE
Integration with Minimap

### ISSUE THREAD

**Issue by JonnyCBB** [Evpok/fancy-bracket-matcher#4]
Thanks for the fantastic package. This has made life so much easier for me. There's another thing that would make like a bit easier. Is it possible to integrate the highlighted package with the minimap? Basically it's for the case where the matching brackets don't fit on the screen (I'm dealing with some long SQL queries).   
Alternatively (or in addition) it would be great if you could hover over the current bracket and a label pops up with the line number of the matching bracket.    

What do you think? I'm not that familiar with JavaScript/CoffeeScript otherwise I would attempt a PR.

Thanks

**Comment by Evpok** [comment]
That's a lot of good ideas, but this package is probably not the right place to implement them. Those things depend on the [`bracket-matcher`](https://github.com/atom/bracket-matcher) package who deals with finding the matching bracket and apply the appropriate style (although the default style is a lot more discreet). Could you please make this feature request there?

**Comment by JonnyCBB** [comment]
Thanks for letting me know. Done! 👍
