### ISSUE TITLE
Bad color choice

### ISSUE THREAD

**Issue by BenoitPoulet** [Evpok/fancy-bracket-matcher#7]
Hello,

Since release 2.0 the colors are not very visible in dark theme :
![capture](https://user-images.githubusercontent.com/2464712/30314368-cd95a634-97a0-11e7-866f-062ebd4c2bdd.PNG)

Barely visible

Regards.

**Comment by Evpok** [comment]
As of 2.0 the colour is dependent of your syntax theme (specifically it is `@syntax-selection-flash-color` but I am open to suggestion regarding which theme variable would be best). I'd like to provide a setting to override it (but that might take some time, so I'd be glad for any PR, even stubby).

**Comment by Evpok** [comment]
[v2.1.0](https://github.com/Evpok/fancy-bracket-matcher/releases/tag/v2.1.0) changes the colour back to the original orange, unless your syntax-theme overrides  `@syntax-color-modified`.
